---
title: "First Knit"
author: "Kiara Butler"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
   The high school I attended to is Lancaster High School, yes I graduated in class of 2023, I found that English is easier for me , The classes I did best in is English,Civics.  

     

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
 I'm using windows for the computer, from a scale 1- 10 my dummy score is 5 I don't know a lot about computer, I rate myself a 10, yes I have internet access, the internet at home is a little slow but it works. 
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  The name I prefer is Kiara, I would like to be called the same name as my buddy's do Kiara.
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
   I just want to be successful and make my family proud,the one subject that will interest me is English, Criminology, History, the degree/ certificate is my AA degree in Law    
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  I've never been to a foreign countries, I would want to go to El Salvador,No I have not been in the military, I would never join the military.   
   
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  No, I have never taken math 115 Im taking math 116 this year, No I didn't know that I don't know you what grade but hopefully its a A,n my plan is to graduate with straight A's from AVC and transfer to a 4 year to Finnish schooling and get my masters degree.
   
 






  




